2024-11-13 02:16:16,040 | INFO | "test_challenge" выполнен успешно
2024-11-13 02:16:16,040 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-13 02:16:16,042 | WARNING | Traceback (most recent call last):
  File "/Users/sergey/Library/Mobile Documents/com~apple~CloudDocs/Documents/PycharmProjects/pythonProject/Urban/12/tests_12_4.py", line 80, in test_run
    runner = Runner(2)
  File "/Users/sergey/Library/Mobile Documents/com~apple~CloudDocs/Documents/PycharmProjects/pythonProject/Urban/12/tests_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-13 02:16:16,042 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-13 02:16:16,042 | WARNING | Traceback (most recent call last):
  File "/Users/sergey/Library/Mobile Documents/com~apple~CloudDocs/Documents/PycharmProjects/pythonProject/Urban/12/tests_12_4.py", line 69, in test_walk
    runner = Runner("Вася", -5)
             ~~~~~~^^^^^^^^^^^^
  File "/Users/sergey/Library/Mobile Documents/com~apple~CloudDocs/Documents/PycharmProjects/pythonProject/Urban/12/tests_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

